{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       AssertionError: \u274c Test failed due to mismatches\n       assert False\n", "test_name": "test_adt_0002", "rerun": "0"}}, "suite_name": "test/test_audittrail.py"}}}, "date": "March 03, 2025", "start_time": 1740970889.7960086, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}